version: '3' 
services:  
  server:  
    build: .  
    ports:  
      - "5000:80"  
    depends_on:  
      - db  
    env_file:  
      - ./.env  
    volumes:  
      - .:/app
  db:  
    image: postgres  
    environment:  
      - POSTGRES_PASSWORD=local_password
      - POSTGRES_DB=local_db  
    volumes:  
      - postgres_data:/var/lib/postgresql/data  
volumes:  
  postgres_data: