"""empty message

Revision ID: c4cca7464551
Revises: ea106b3cd827
Create Date: 2024-10-09 09:35:13.338007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from ts_vector import TSVector

# revision identifiers, used by Alembic.
revision = 'c4cca7464551'
down_revision = 'ea106b3cd827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.Enum('TO_WATCH', 'WATCHING', 'COMPLETED', 'ABANDONED', 'ON_HOLD', name='seriesstatusenum'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('creation_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ts_series_vector', TSVector(), sa.Computed("to_tsvector('english', title || ' ' || description)", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index('ix_series___ts_vector__', ['ts_series_vector'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index('ix_series___ts_vector__', postgresql_using='gin')

    op.drop_table('series')
    # ### end Alembic commands ###
