"""empty message

Revision ID: ea106b3cd827
Revises: ef3ba0042010
Create Date: 2024-10-05 14:09:03.761578

"""
from alembic import op
import sqlalchemy as sa
from ts_vector import TSVector


# revision identifiers, used by Alembic.
revision = 'ea106b3cd827'
down_revision = 'ef3ba0042010'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ts_book_vector', TSVector(), sa.Computed("to_tsvector('english', title || ' ' || description || ' ' || author)", persisted=True), nullable=True))
        batch_op.create_index('ix_book___ts_vector__', ['ts_book_vector'], unique=False, postgresql_using='gin')

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ts_movie_vector', TSVector(), sa.Computed("to_tsvector('english', title || ' ' || description)", persisted=True), nullable=True))
        batch_op.create_index('ix_movie___ts_vector__', ['ts_movie_vector'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_index('ix_movie___ts_vector__', postgresql_using='gin')
        batch_op.drop_column('ts_movie_vector')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index('ix_book___ts_vector__', postgresql_using='gin')
        batch_op.drop_column('ts_book_vector')

    # ### end Alembic commands ###
